[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "NX_SKIP_NX_CLOUD=true nx build angular-app --configuration=production"
  publish = "dist/apps/angular-app/browser"

[build.environment] 
  NPM_FLAGS = "--force --loglevel=error"